
=head1 NAME

gosa-encrypt-passwords - Encrypt your gosa.conf passwords with a master password

=head1 SYNOPSIS

gosa-encrypt-passwords

=head1 DESCRIPTION

gosa-encrypt-passwords is a script to encrypt your gosa.conf passwords
with a master password. Your passwords are then only readable by the GOsa
location. 

