<table summary="" style="width:100%;">
 <tr>
  <td style="width:50%; vertical-align:top;">
   <input type="hidden" name="groupedit" value="1">
   <table summary="">
    <tr>
     <td>{t}Group name{/t}{$must}</td>
     <td>
       <input name="cn" size=25 maxlength=60 {$cnACL} value="{$cn}" title="{t}Posix name of the group{/t}">
     </td>
    </tr>
    <tr>
     <td>{t}Description{/t}</td>
     <td><input name="description" size=40 maxlength=60 {$descriptionACL} value="{$description}" title="{t}Descriptive text for this group{/t}">
     </td>
    </tr>
    <tr>
      <td colspan=2> <div style="height:15px;"></div> </td>
    </tr>
    <tr>
     <td>{t}Base{/t}{$must}</td>
     <td>
      <select size="1" name="base" {$baseACL} title="{t}Choose subtree to place group in{/t}">
       {html_options options=$bases selected=$base_select}
      </select>
     </td>
    </tr>
    <tr>
      <td colspan=2> <div style="height:15px; width:100%; border-bottom:1px solid #909090;"></div> </td>
    </tr>
    <tr>
      <td colspan=2> <div style="height:15px; width:100%;"></div> </td>
    </tr>
    <tr>
     <td colspan=2>
      <input type=checkbox name="force_gid" value="1" title="{t}Normally IDs are autogenerated, select to specify manually{/t}" {$force_gid} {$force_gidACL} onclick="changeState('gidNumber')">{t}Force GID{/t}
      &nbsp;
      <input name="gidNumber" size=5 maxlength=5 id="gidNumber" {$gidNumberACL} {$forceMode} value="{$gidNumber}" title="{t}Forced ID number{/t}">
     </td>
    </tr>

    {if $samba3 ne ""}
    <tr>
     <td colspan=2>
      <input type=checkbox name="smbgroup" value="1" {$smbgroup} {$smbgroupACL} title="{t}Select to create a samba conform group{/t}">
      <select size="1" name="groupType" {$sambaDomainNameACL}>
       {html_options options=$groupTypes selected=$groupType}
      </select>
      &nbsp;
      {t}in domain{/t}
      &nbsp;
      <select size="1" name="sambaDomainName" {$sambaDomainNameACL}>
       {html_options values=$sambaDomains output=$sambaDomains selected=$sambaDomainName}
      </select>
     </td>
    </tr>
    {/if}
    <tr>
      <td colspan=2> <div style="height:15px; width:100%; border-bottom:1px solid #909090;"></div> </td>
    </tr>
    <tr>
      <td colspan=2> <div style="height:15px; width:100%;"></div> </td>
    </tr>
    <tr>
     <td colspan=2>
      <input type=checkbox name="fon_group" value="1" {$fon_group} {$fon_groupACL}>{t}Members are in a phone pickup group{/t}
     </td>
    </tr>
   </table>

  </td>
  <td style="border-left:1px solid #A0A0A0">
   &nbsp;
  </td>

  <td style="vertical-align:top;">

   <table summary="">
    <tr>
     <td style="vertical-align:top;">
      <b>{t}Group members{/t}</b>
      <br>
      <select style="width:400px; height:300px;" name="members[]" size=15 multiple>
       {html_options options=$members}
		<option disabled></option>
      </select>
      <br>
      <input type=submit name="edit_membership" value="{t}Add{/t}" {$membersACL}>
      &nbsp;
      <input type=submit name="del_users" value="{t}Delete{/t}" {$membersACL}>
     </td>
    </tr> 
   </table>
  </td>

 </tr>
</table>

<!-- Place cursor -->
<script language="JavaScript" type="text/javascript">
  <!-- // First input field on page
  document.mainform.cn.focus();
  -->
</script>
