.TH GOSA-ENCRYPT-PASSWORDS 1
.SH NAME
gosa-encrypt-passwords \- gosa-encrypt-password a tool to encrypt password stored in gosa.conf
.SH SYNOPSIS
.PP
.B gosa-encrypt-passwords
.SH DESCRIPTION
.I gosa-encrypt-passwords
takes the password found in the gosa.conf file and create a 
.B gosa.secrets
file read by apache when gosa is used.
