.TH MNTPASSWD 1
.SH NAME
mkntpasswd \- mkntpasswd a tool to generate samba password hashes
.SH SYNOPSIS
.PP
.B mkntpasswd
.I password
.SH DESCRIPTION
.I mkntpasswd
takes the password supplied on the command line and prints the corresponding
.I samba
password hash to STDOUT.

.SH "BUGS"
.IX Header "BUGS"
Please report any bugs, or post any suggestions, to the GOsa mailing list <gosa\-devel@oss.gonicus.de> or to <https://oss.gonicus.de/labs/gosa>
.SH "LICENCE AND COPYRIGHT"
.IX Header "LICENCE AND COPYRIGHT"
This code is part of GOsa (<http://www.gosa\-project.org>)
.PP
Copyright (C) 2003\-2008 \s-1GONICUS\s0 GmbH
.PP
This program is distributed in the hope that it will be useful,
but \s-1WITHOUT\s0 \s-1ANY\s0 \s-1WARRANTY\s0; without even the implied warranty of
\&\s-1MERCHANTABILITY\s0 or \s-1FITNESS\s0 \s-1FOR\s0 A \s-1PARTICULAR\s0 \s-1PURPOSE\s0.  See the
\&\s-1GNU\s0 General Public License for more details.

