<?php
$class_mapping= array(
                "Registry" => "include/class_Registry.inc",
                "ConfigManagerException" => "include/class_ConfigManager.inc",
                "ConfigManager" => "include/class_ConfigManager.inc",
                "AutoloadException" => "include/autoload.inc",
                "ObjectListException" => "include/class_ObjectList.inc",
                "ObjectList" => "include/class_ObjectList.inc",
                "GOsaGuiElement" => "include/class_GOsaGuiElement.inc",
                "ObjectListFilterIterator" => "include/class_ObjectListFilterIterator.inc",
                "ObjectListViewportException" => "include/class_ObjectListViewport.inc",
                "ObjectListViewport" => "include/class_ObjectListViewport.inc",
                "ObjectListIterator" => "include/class_ObjectListIterator.inc",
                "ObjectListEntryFilter" => "include/interface_ObjectListEntryFilter.inc",
                "GOsaGuiElementInteraction" => "include/interface_GOsaGuiElementInteraction.inc",
                "ObjectListEntryFilter_uppercase" => "include/class_ObjectListEntryFilter_uppercase.inc",
);
?>