<?php
$class_mapping= array(
                "Registry" => "include/class_Registry.inc",
                "ConfigManagerException" => "include/class_ConfigManager.inc",
                "ConfigManager" => "include/class_ConfigManager.inc",
                "AutoloadException" => "include/autoload.inc",
                "ObjectListEntryFilter" => "include/interface_objectListEntryFilter.inc",
                "ObjectListException" => "include/class_ObjectList.inc",
                "ObjectList" => "include/class_ObjectList.inc",
                "ObjectListEntryFilter_uppercase" => "include/class_objectListEntryFilter_uppercase.inc",
                "ObjectListFilterIterator" => "include/class_ObjectListFilterIterator.inc",
                "ObjectListViewportException" => "include/class_ObjectListViewport.inc",
                "ObjectListViewport" => "include/class_ObjectListViewport.inc",
                "ObjectListIterator" => "include/class_ObjectListIterator.inc",
);
?>