<h1>{t}Setup finished{/t}</h1>

{t}Basically the setup is finished. You can check the result of the schema check here and download the autogenerated gosa.conf below.{/t}

<p class="seperator">&nbsp;</p>

<h2>{t}Schema Configuration{/t}</h2>
<p>{$schemas}</p>

<p class="seperator">&nbsp;</p>

<h2>{t}Configuration File{/t}</h2>
<p>
 {t}GOsa setup has collected all data needed to create an initial configuration file. Save the the link below as your gosa.conf and place that file in /etc/gosa. Change it as needed.{/t}
</p>

<input type='submit' name='getconf' value='{t}Download configuration{/t}'>

<p>
 {t}After placing the file under /etc/gosa, place make sure that the webserver user is able to read gosa.conf, while other users shouldn't. You may want to execute these commands to achieve this requirement:{/t}
</p>

<pre>
# chown root.{$webgroup} /etc/gosa/gosa.conf
# chmod 640 /etc/gosa/gosa.conf
</pre>

<p class="plugbottom">
  <input type="hidden" name="next" value="6">
  <input type='submit' name='back' value='{t}Back{/t}'>
  <input type='submit' name='retry' value='{t}Retry{/t}'>
</p>
